/* eslint-disable prettier/prettier */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

type ComponentRegistry = Record<
  string,
  Record<
    string,
    {
      name: string
      story: string
      component: string
      file: string
    }
  >
>

export const Index: ComponentRegistry = {
  "Breadcrumbs": {
    "default": {
      name: "Breadcrumbs-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Breadcrumbs/default")),
      file: "registry/Breadcrumbs/default.tsx"
    },
  },
  "Button": {
    "default": {
      name: "Button-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Button/default")),
      file: "registry/Button/default.tsx"
    },
  },
  "Calendar": {
    "default": {
      name: "Calendar-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Calendar/default")),
      file: "registry/Calendar/default.tsx"
    },
  },
  "Checkbox": {
    "default": {
      name: "Checkbox-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Checkbox/default")),
      file: "registry/Checkbox/default.tsx"
    },
  },
  "CheckboxGroup": {
    "default": {
      name: "CheckboxGroup-default",
      story: "default",
      component: React.lazy(() => import("@/registry/CheckboxGroup/default")),
      file: "registry/CheckboxGroup/default.tsx"
    },
  },
  "Combobox": {
    "default": {
      name: "Combobox-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Combobox/default")),
      file: "registry/Combobox/default.tsx"
    },
  },
  "DateField": {
    "default": {
      name: "DateField-default",
      story: "default",
      component: React.lazy(() => import("@/registry/DateField/default")),
      file: "registry/DateField/default.tsx"
    },
  },
  "DateInput": {
    "default": {
      name: "DateInput-default",
      story: "default",
      component: React.lazy(() => import("@/registry/DateInput/default")),
      file: "registry/DateInput/default.tsx"
    },
  },
  "DatePicker": {
    "default": {
      name: "DatePicker-default",
      story: "default",
      component: React.lazy(() => import("@/registry/DatePicker/default")),
      file: "registry/DatePicker/default.tsx"
    },
  },
  "DateRangePicker": {
    "default": {
      name: "DateRangePicker-default",
      story: "default",
      component: React.lazy(() => import("@/registry/DateRangePicker/default")),
      file: "registry/DateRangePicker/default.tsx"
    },
  },
  "GridList": {
    "default": {
      name: "GridList-default",
      story: "default",
      component: React.lazy(() => import("@/registry/GridList/default")),
      file: "registry/GridList/default.tsx"
    },
  },
  "IconButton": {
    "default": {
      name: "IconButton-default",
      story: "default",
      component: React.lazy(() => import("@/registry/IconButton/default")),
      file: "registry/IconButton/default.tsx"
    },
  },
  "Input": {
    "default": {
      name: "Input-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Input/default")),
      file: "registry/Input/default.tsx"
    },
  },
  "Label": {
    "default": {
      name: "Label-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Label/default")),
      file: "registry/Label/default.tsx"
    },
  },
  "Menu": {
    "default": {
      name: "Menu-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Menu/default")),
      file: "registry/Menu/default.tsx"
    },
  },
  "Meter": {
    "default": {
      name: "Meter-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Meter/default")),
      file: "registry/Meter/default.tsx"
    },
  },
  "Modal": {
    "default": {
      name: "Modal-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Modal/default")),
      file: "registry/Modal/default.tsx"
    },
  },
  "NumberField": {
    "default": {
      name: "NumberField-default",
      story: "default",
      component: React.lazy(() => import("@/registry/NumberField/default")),
      file: "registry/NumberField/default.tsx"
    },
    "mobile": {
      name: "NumberField-mobile",
      story: "mobile",
      component: React.lazy(() => import("@/registry/NumberField/mobile")),
      file: "registry/NumberField/mobile.tsx"
    },
  },
  "ProgressBar": {
    "default": {
      name: "ProgressBar-default",
      story: "default",
      component: React.lazy(() => import("@/registry/ProgressBar/default")),
      file: "registry/ProgressBar/default.tsx"
    },
  },
  "Radio": {
    "default": {
      name: "Radio-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Radio/default")),
      file: "registry/Radio/default.tsx"
    },
  },
  "RadioGroup": {
    "default": {
      name: "RadioGroup-default",
      story: "default",
      component: React.lazy(() => import("@/registry/RadioGroup/default")),
      file: "registry/RadioGroup/default.tsx"
    },
  },
  "RangeCalendar": {
    "default": {
      name: "RangeCalendar-default",
      story: "default",
      component: React.lazy(() => import("@/registry/RangeCalendar/default")),
      file: "registry/RangeCalendar/default.tsx"
    },
  },
  "SearchField": {
    "default": {
      name: "SearchField-default",
      story: "default",
      component: React.lazy(() => import("@/registry/SearchField/default")),
      file: "registry/SearchField/default.tsx"
    },
    "with-clear-button": {
      name: "SearchField-with-clear-button",
      story: "with-clear-button",
      component: React.lazy(() => import("@/registry/SearchField/with-clear-button")),
      file: "registry/SearchField/with-clear-button.tsx"
    },
    "with-label": {
      name: "SearchField-with-label",
      story: "with-label",
      component: React.lazy(() => import("@/registry/SearchField/with-label")),
      file: "registry/SearchField/with-label.tsx"
    },
  },
  "Select": {
    "default": {
      name: "Select-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Select/default")),
      file: "registry/Select/default.tsx"
    },
  },
  "Slider": {
    "default": {
      name: "Slider-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Slider/default")),
      file: "registry/Slider/default.tsx"
    },
    "vertical": {
      name: "Slider-vertical",
      story: "vertical",
      component: React.lazy(() => import("@/registry/Slider/vertical")),
      file: "registry/Slider/vertical.tsx"
    },
  },
  "Switch": {
    "default": {
      name: "Switch-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Switch/default")),
      file: "registry/Switch/default.tsx"
    },
  },
  "Tabs": {
    "default": {
      name: "Tabs-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Tabs/default")),
      file: "registry/Tabs/default.tsx"
    },
    "vertical": {
      name: "Tabs-vertical",
      story: "vertical",
      component: React.lazy(() => import("@/registry/Tabs/vertical")),
      file: "registry/Tabs/vertical.tsx"
    },
  },
  "TextField": {
    "default": {
      name: "TextField-default",
      story: "default",
      component: React.lazy(() => import("@/registry/TextField/default")),
      file: "registry/TextField/default.tsx"
    },
    "with-error": {
      name: "TextField-with-error",
      story: "with-error",
      component: React.lazy(() => import("@/registry/TextField/with-error")),
      file: "registry/TextField/with-error.tsx"
    },
    "with-label": {
      name: "TextField-with-label",
      story: "with-label",
      component: React.lazy(() => import("@/registry/TextField/with-label")),
      file: "registry/TextField/with-label.tsx"
    },
  },
  "Tooltip": {
    "default": {
      name: "Tooltip-default",
      story: "default",
      component: React.lazy(() => import("@/registry/Tooltip/default")),
      file: "registry/Tooltip/default.tsx"
    },
  },
};
